CREATE TABLE IF NOT EXISTS `auth` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `authorid` VARCHAR(50) NOT NULL,
    `token` TEXT NOT NULL UNIQUE,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `recreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;